### PR TITLE
Prep 0.31.0

### PR DESCRIPTION
**Pull request by kyleve**

### CODE REVIEW

**Review by kylebshr — COMMENTED** [review]
Not to be pedantic, but this isn't a minor bug fix so it should be `0.31.0`

**Comment by kyleve** [comment]
True, I guess I considered the caching and better error messages "fixes", not really new un-breaking features, but 0.31.0 is easy enough...

**Comment by kyleve** [comment]
Switched to 0.31.0, if anyone feels strongly I can switch it back to 0.30.1 too

**Review by n8chur — APPROVED** [review]
Make sure you update the PR description if you decide to keep it `0.31.0`

**Pull request merged**
