### PR TITLE
Bump versions to 0.21.0

### PR DESCRIPTION
**Pull request by kylebshr**

### CODE REVIEW

**Review by kyleve — APPROVED** [review]
Thanks for doing this! I was just gonna get started, but happy to have someone else do it 🙈

**Comment by kylebshr** [comment]
I am the on call 😉

**Comment by kylebshr** [comment]
Oh did you publish? Thanks 🙏

**Comment by kyleve** [comment]
Yeah – oops sorry thought I posted here. I wanted this in SPOS since I was updating my in-progress PRs, and needed the overlay thing to resolve a TODO

**Pull request merged**
