### PR TITLE
Update Tutorial2.md

### PR DESCRIPTION
**Pull request by cbowns**
Fixed up a few arguments which have changed order.

### CODE REVIEW

**Comment by cbowns** [comment]
Couple other changes here, one sec.

**Comment by bencochran** [comment]
Thanks!

Side-note: I wonder if we should be pushing people to use `.inset(…)` and `.constrainedTo`? (Thoughts, @kyleve?)

**Comment by kyleve** [comment]
Yeah, seems like a good idea for us to update the demos to use the swiftui syntax

**Comment by bencochran** [comment]
Filed #131

**Pull request merged**
